IF COL_LENGTH('dbo.SOLICITUD_DOCUMENTO', 'ArchivoContenido') IS NULL
BEGIN
    ALTER TABLE dbo.SOLICITUD_DOCUMENTO
    ADD ArchivoContenido VARBINARY(MAX) NULL;
END;

IF COL_LENGTH('dbo.SOLICITUD_DOCUMENTO', 'ContentType') IS NULL
BEGIN
    ALTER TABLE dbo.SOLICITUD_DOCUMENTO
    ADD ContentType VARCHAR(150) NULL;
END;
