IF COL_LENGTH('dbo.SOLICITUD_TESIS', 'FechaPresentacion') IS NULL
BEGIN
    ALTER TABLE dbo.SOLICITUD_TESIS
    ADD FechaPresentacion DATETIME NULL;
END;

IF OBJECT_ID('dbo.CARRERA_ESTADO_SOLICITUD', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CARRERA_ESTADO_SOLICITUD
    (
        IdCarreraEstadoSolicitud INT IDENTITY(1,1) NOT NULL,
        IdCarrera INT NOT NULL,
        IdEstadoSolicitud INT NOT NULL,
        Orden INT NOT NULL,
        RequiereFechaPresentacion BIT NOT NULL CONSTRAINT DF_CES_REQUIERE_FECHA DEFAULT (0),
        Activo CHAR(1) NULL CONSTRAINT DF_CES_ACTIVO DEFAULT ('S'),
        CONSTRAINT PK_CARRERA_ESTADO_SOLICITUD PRIMARY KEY (IdCarreraEstadoSolicitud),
        CONSTRAINT UQ_CES_CARRERA_ESTADO UNIQUE (IdCarrera, IdEstadoSolicitud),
        CONSTRAINT UQ_CES_CARRERA_ORDEN UNIQUE (IdCarrera, Orden),
        CONSTRAINT FK_CES_CARRERA FOREIGN KEY (IdCarrera) REFERENCES dbo.CARRERA(IdCarrera),
        CONSTRAINT FK_CES_ESTADO_SOLICITUD FOREIGN KEY (IdEstadoSolicitud) REFERENCES dbo.ESTADO_SOLICITUD(IdEstadoSolicitud)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM dbo.MODULOS
    WHERE IdModulo = '01'
)
BEGIN
    INSERT INTO dbo.MODULOS (IdModulo, DESCRIPCION)
    VALUES ('01', 'Sistema');
END;

IF NOT EXISTS (
    SELECT 1
    FROM dbo.FORMAS
    WHERE IdModulo = '01' AND NOM_FORMA = 'FLUJOTES'
)
BEGIN
    INSERT INTO dbo.FORMAS (IdModulo, NOM_FORMA, DESCRIPCION)
    VALUES ('01', 'FLUJOTES', 'Flujo de Tesis');
END;
