IF OBJECT_ID('dbo.CARRERA_FLUJO_TRANSICION', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CARRERA_FLUJO_TRANSICION
    (
        IdCarreraFlujoTransicion INT IDENTITY(1,1) NOT NULL,
        IdCarrera INT NOT NULL,
        IdEstadoOrigen INT NOT NULL,
        IdEstadoDestino INT NOT NULL,
        Accion VARCHAR(100) NOT NULL,
        RequiereComentario BIT NOT NULL CONSTRAINT DF_CFT_REQUIERE_COMENTARIO DEFAULT (0),
        RequiereFechaPresentacion BIT NOT NULL CONSTRAINT DF_CFT_REQUIERE_FECHA DEFAULT (0),
        Activo CHAR(1) NULL CONSTRAINT DF_CFT_ACTIVO DEFAULT ('S'),
        CONSTRAINT PK_CARRERA_FLUJO_TRANSICION PRIMARY KEY (IdCarreraFlujoTransicion),
        CONSTRAINT FK_CFT_CARRERA FOREIGN KEY (IdCarrera) REFERENCES dbo.CARRERA(IdCarrera),
        CONSTRAINT FK_CFT_ESTADO_ORIGEN FOREIGN KEY (IdEstadoOrigen) REFERENCES dbo.ESTADO_SOLICITUD(IdEstadoSolicitud),
        CONSTRAINT FK_CFT_ESTADO_DESTINO FOREIGN KEY (IdEstadoDestino) REFERENCES dbo.ESTADO_SOLICITUD(IdEstadoSolicitud)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM dbo.MODULOS
    WHERE IdModulo = '01'
)
BEGIN
    INSERT INTO dbo.MODULOS (IdModulo, DESCRIPCION)
    VALUES ('01', 'Sistema');
END;

IF NOT EXISTS (
    SELECT 1
    FROM dbo.FORMAS
    WHERE IdModulo = '01' AND NOM_FORMA = 'FLUJOTES'
)
BEGIN
    INSERT INTO dbo.FORMAS (IdModulo, NOM_FORMA, DESCRIPCION)
    VALUES ('01', 'FLUJOTES', 'Flujo de Tesis');
END;
