IF OBJECT_ID('dbo.GRUPOS_ESTADOS_SOLICITUD', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GRUPOS_ESTADOS_SOLICITUD
    (
        IdGrupo VARCHAR(6) NOT NULL,
        IdEstadoSolicitud INT NOT NULL,
        CONSTRAINT PK_GRUPOS_ESTADOS_SOLICITUD PRIMARY KEY (IdGrupo, IdEstadoSolicitud),
        CONSTRAINT FK_GES_GRUPO FOREIGN KEY (IdGrupo)
            REFERENCES dbo.GRUPOS_USUARIOS(IdGrupo),
        CONSTRAINT FK_GES_ESTADO_SOLICITUD FOREIGN KEY (IdEstadoSolicitud)
            REFERENCES dbo.ESTADO_SOLICITUD(IdEstadoSolicitud)
    );
END;
